### ISSUE TITLE
[NERSC] Difference Image Analysis shared sandbox area

### ISSUE THREAD

**Issue by BrunoSanchez** [LSSTDESC/desc-help#6] opened 2020-02-16 17:16 UTC
This request asks for a shared/common space in NERSC for the DIA topical team to use a running version of `dia_pipe`

This would include a running version of the pipeline software accessible through a simple setup command. We would also need some disk space to share input/output among DIA T.T. members and also to share results to the collaboration. 

This should solve the need of having a quick path for a new member of the DIA team to start running the pipeline and producing image subtractions. 

Choose all applicable topics by placing an 'X' between the [ ]:
- [ ] jupyter
- [x] Cori interactive command line
- [x] Batch jobs
- [ ] python
- [ ] CSCRATCH
- [x] Community File System
- [ ] HPSS (tape)
- [ ] Data transfer and Globus
- [ ] New User Account or account access problems

**Comment by heather999** [comment] 2020-02-18 14:35
Hi @BrunoSanchez @wmwv
We can set up a group area for DIA in the new NERSC Community File Space. Do you have any estimate on total disk requirements?

To set up `dia_pipe`, is there some current list of software requirements:  version of DMstack (`w_2019_19`?), `obs_lsst`, etc?  Writing up a set up script based on CVMFS and/or potentially setting up a docker/shifter image is possible.  I think we'd want to add to setup script to the `dia_pipe` repo?  An example of how things are setup and run currently, would help.

**Comment by BrunoSanchez** [comment] 2020-02-18 15:17
Hi @heather999 
I have for 2 square degrees, summing templates, differences and catalogs, roughly 1.5T of used space in SCRATCH. I think that 3T would be more than enough (I don't know if I am asking more than you can do).

Regarding the setup script I have the following Gist: [https://gist.github.com/BrunoSanchez/87b15538cfc8bc8cd187d07073cb8c6d](Gist).
However there were recent merges in `dia_pipe` and probably Bob and Johan can correct this for the latest version.

**Comment by johannct** [comment] 2020-02-18 15:35
ok so looking at the gist you really only need the group space setup. The config is just a matter of sourcing the cvmfs stack release and developing on obs_lsst and dia_pipe, which are both in dev anyway. So once the CFS space is set up, I would be in favor that you install in there the software you want to share and provide a setup script for the collaborators to use this sandbox. I do not see any reason to containerize or to do something more involved at this stage, correct?

**Comment by heather999** [comment] 2020-02-20 00:18
The remaining issue with using CVMFS at NERSC involves whether or not one is compiling actual C/C++ code against the CVMFS installation - as we will encounter ABI incompatibilities. That is an area where using a container works better, never mind the clearer archive of software versions.  But, I know `obs_lsst` will be fine to setup against CVMFS, and from what I can see `dia-pipe` is just python code, so that should be ok as well.
For performance reasons, CFS may not be the best place to install local copies of `dia-pipe` and `obs_lsst`, here again, a container will perform better, but we can try it out and see what happens for development purposes.  I would suggest storing any setup script within `dia-pipe` so that it can be tagged and versioned as you guys go along.  For fun, I'll probably set up a repo to build a docker container so it'll be available if it's needed, and in the end any DIA maintainers can create a new image when software updates are necessary.

I have put in the request to NERSC to set up a general SN area, which will include the DIA area, where planning to use 3 TB will be fine - just waiting for the new directory to show up in the CFS. The area will be RW by all DESC NERSC users.

**Comment by heather999** [comment] 2020-02-20 18:03
@BrunoSanchez there is now a new `/global/cfs/cdirs/lsst/groups/SN/dia` directory.  It is RW by all DESC NERSC users.  
The next step would be to install copies of `dia_pipe` and `obs_lsst` under some directory in this area.  You might want installations for both DMstack `w_2019_19` and `v19`.  For `v19`, it looks like you want `obs_lsst` `dc2/run2.2` and `master` of `dia_pipe`. Has anyone confirmed that `v19` will work if you continue to process Run2.1i data? It should, but there are sometimes incompatibilities. Anyway, to get you going, I just installed `dia_pipe` master and `obs_lsst` `dc2/run2.2` built against DMstack v19, along with a setup script in: `/global/cfs/cdirs/lsst/groups/SN/dia/code/v19`  and made a PR for the setup script: https://github.com/LSSTDESC/dia_pipe/pull/8

**Comment by BrunoSanchez** [comment] 2020-02-21 15:03
@heather999 this is awesome. I will need to check this configuration to confirm that `v19` is working with Run2.1i data. is a matter of just trying and checking the results.

Thanks for the pull request, it seems exactly what we need.

**Comment by heather999** [comment] 2020-02-27 18:58
Hi @BrunoSanchez I'm going to close this issue - but if anything comes up, please feel free to reopen this issue or create a new one.

**Closed by heather999** 2020-02-27 18:58 UTC
Labels: nersc
